[package]
name = "stellar-payment-messaging-system"
version = "0.1.0"
edition = "2021"

[dependencies]
soroban-sdk = "21.7.4"

[dev-dependencies]
soroban-sdk = { version = "21.7.4", features = ["testutils"] }

[lib]
crate-type = ["cdylib"]

[features]
testutils = ["soroban-sdk/testutils"]